plotNcpResultsFromSettingsFile("NCPSettings.xml")

% plotTreatmentOptimizationJointLoads( ...
%     fullfile("preprocessedNCP", "IDData", "drive_kick1.sto"), ...
%     fullfile("preprocessed", "IDData", "drive_kick1.sto"))
% 
% plotTreatmentOptimizationJointAngles( ...
%     "KickingModel.osim", ...
%     fullfile("preprocessedNCP", "IKData", "drive_kick1.sto"), ...
%     fullfile("preprocessedTO", "IKData", "drive_kick1.sto"))

