function [pathTerm, constraintTerm] = calcUserDefinedKineticConsistency( ...
	values, modeledValues, inputs, constraintTerm)
[inverseDynamicsLoad, constraintTerm] = findDataByLabels( ...
    constraintTerm, modeledValues.inverseDynamicsMoments, ...
    inputs.inverseDynamicsMomentLabels, constraintTerm.load);
[control, constraintTerm] = findControlsByLabels(constraintTerm, inputs, values, ...
    values.time, constraintTerm.control);

pathTerm = inverseDynamicsLoad - control;
end
