
clc; clear; close all;
muscleTendonLengthFileName = "preprocessed\MAData\kick_1\kick_1_Length.sto";
cutoffFrequency = 10;
createMuscleTendonVelocity(muscleTendonLengthFileName, cutoffFrequency);
NeuralControlPersonalizationTool("NCPSettingsFile.xml");

plotNeuralControlPersonalizationActivations( ...
    fullfile("ncpResults", "synergyWeights.sto"), ...
    fullfile("ncpResults", "kick_1_synergyCommands.sto"), ...
    fullfile("mtpResults", "muscleActivations", "kick_1.sto"), ...
    3, 3)