%% Run Torque-Driven Tracking Optimization

TrackingOptimizationTool("TorqueDrivenTrackingOptimizationSettings.xml");

%% Run Synergy-Driven Tracking Optimization

TrackingOptimizationTool("SynergyDrivenTrackingOptimizationSettings.xml");

%% Run Muscle-Driven Tracking Optimization

TrackingOptimizationTool("MuscleDrivenTrackingOptimizationSettings.xml");

%% Plot Results

plotTreatmentOptimizationJointAngles( ...
    "RightLegAndPelvis.osim", ...
    fullfile("preprocessed/IKData/kick_1.sto"), ...
    [fullfile("resultsTO/IKData/kick_1.sto"), ...
    fullfile("SynergyDrivenTO/IKData/kick_1.sto"), ...
    fullfile("MuscleDrivenTO/IKData/kick_1.sto")])

plotTreatmentOptimizationJointLoads( ...
    fullfile("preprocessed/IDData/kick_1.sto"), ...
    [fullfile("resultsTO/IDData/kick_1.sto"), ...
    fullfile("SynergyDrivenTO/IDData/kick_1.sto"), ...
    fullfile("MuscleDrivenTO/IDData/kick_1.sto")])

plotTreatmentOptimizationControls( ...
    fullfile("resultsTO/kick_1_torqueControls.sto"))

plotTreatmentOptimizationControls( ...
    fullfile("SynergyDrivenTO/kick_1_synergyCommands.sto"))

plotTreatmentOptimizationControls( ...
    fullfile("MuscleDrivenTO/kick_1_muscleControls.sto"))

plotTreatmentOptimizationMuscleActivations( ...
    fullfile("ncpResults/kick_1_combinedActivations.sto"), ...
    [fullfile("SynergyDrivenTO/kick_1_combinedActivations.sto"), ...
    fullfile("MuscleDrivenTO/kick_1_combinedActivations.sto")])
