%% Run Torque-Driven Tracking Optimization

TrackingOptimizationTool("TorqueDrivenTrackingOptimizationSettings.xml");

%% Run Synergy-Driven Tracking Optimization

TrackingOptimizationTool("SynergyDrivenTrackingOptimizationSettings.xml");

%% Plot Results

plotTreatmentOptimizationJointAngles( ...
    fullfile("preprocessed/IKData/kick_1.sto"), ...
    [fullfile("resultsTO/IKData/kick_1.sto"), ...
    fullfile("SynergyDrivenTO/IKData/kick_1.sto")])

plotTreatmentOptimizationJointLoads( ...
    fullfile("preprocessed/IDData/kick_1.sto"), ...
    [fullfile("resultsTO/IDData/kick_1.sto"), ...
    fullfile("SynergyDrivenTO/IDData/kick_1.sto")])

plotTreatmentOptimizationTorqueControls( ...
    fullfile("resultsTO/kick_1_torqueControls.sto"))

plotTreatmentOptimizationSynergyControls( ...
    fullfile("SynergyDrivenTO/kick_1_synergyCommands.sto"))

plotTreatmentOptimizationMuscleActivations( ...
    fullfile("ncpResults/kick_1_combinedActivations.sto"), ...
    fullfile("SynergyDrivenTO/kick_1_combinedActivations.sto"))
