%% Run NCP

NeuralControlPersonalizationTool("NCPSettings.xml")

%% Analyze results

plotNeuralControlPersonalizationActivations( ...
    fullfile("ncpResults", "synergyWeights.sto"), ...
    fullfile("ncpResults", "gait_1_synergyCommands.sto"), ...
    fullfile("mtpResults", "muscleActivations", "gait_1_muscleActivations.sto"), ...
    3, 3)

plotNcpActivationRmsAndVaf(fullfile("ncpResults", "synergyWeights.sto"), ...
    fullfile("ncpResults", "gait_1_synergyCommands.sto"), ...
    fullfile("mtpResults", "muscleActivations", "gait_1_muscleActivations.sto"))
