%% Run NCP

NeuralControlPersonalizationTool("NCPSettings.xml")

%% Analyze results

close all

figure(1)
plotNeuralControlPersonalizationActivations( ...
    fullfile("ncpResults", "synergyWeights.sto"), ...
    fullfile("ncpResults", "gait_1_synergyCommands.sto"), ...
    fullfile("mtpResults", "muscleActivations", "gait_1_muscleActivations.sto"), ...
    3, 3)

figure(2)
plotNcpActivationRmsAndVaf(fullfile("ncpResults", "synergyWeights.sto"), ...
    fullfile("ncpResults", "gait_1_synergyCommands.sto"), ...
    fullfile("mtpResults", "muscleActivations", "gait_1_muscleActivations.sto"))
