%% Run Torque-Driven Verification Optimization

VerificationOptimizationTool("TorqueDrivenVerificationOptimizationSettings.xml");

%% Run Synergy-Driven Verification Optimization

VerificationOptimizationTool("SynergyDrivenVerificationOptimizationSettings.xml");

%% Run Muscle-Driven Verification Optimization

VerificationOptimizationTool("MuscleDrivenVerificationOptimizationSettings.xml");

%% Plot Torque-Driven Results

plotTreatmentOptimizationJointAngles( ...
    "RightLegAndPelvis.osim", ...
    fullfile("../Step-7-Tracking-Optimization/resultsTO/IKData/kick_1.sto"), ...
    fullfile("resultsVO/IKData/kick_1.sto"))

plotTreatmentOptimizationJointLoads( ...
    fullfile("../Step-7-Tracking-Optimization/resultsTO/IDData/kick_1.sto"), ...
    fullfile("resultsVO/IDData/kick_1.sto"))

plotTreatmentOptimizationTorqueControls( ...
    fullfile("resultsVO/kick_1_torqueControls.sto"))

%% Plot Synergy-Driven Results

plotTreatmentOptimizationJointAngles( ...
     "RightLegAndPelvis.osim", ...
    fullfile("../Step-7-Tracking-Optimization/SynergyDrivenTO/IKData/kick_1.sto"), ...
    fullfile("SynergyDrivenVO/IKData/kick_1.sto"))

plotTreatmentOptimizationJointLoads( ...
    fullfile("../Step-7-Tracking-Optimization/SynergyDrivenTO/IDData/kick_1.sto"), ...
    fullfile("SynergyDrivenVO/IDData/kick_1.sto"))

plotTreatmentOptimizationSynergyControls( ...
    fullfile("SynergyDrivenVO/kick_1_synergyCommands.sto"))

plotTreatmentOptimizationMuscleActivations( ...
    fullfile("../Step-7-Tracking-Optimization/SynergyDrivenTO/kick_1_combinedActivations.sto"), ...
    fullfile("SynergyDrivenVO/kick_1_combinedActivations.sto"))

%% Plot Muscle-Driven Results

plotTreatmentOptimizationJointAngles( ...
     "RightLegAndPelvis.osim", ...
    fullfile("../Step-7-Tracking-Optimization/MuscleDrivenTO/IKData/kick_1.sto"), ...
    fullfile("MuscleDrivenVO/IKData/kick_1.sto"))

plotTreatmentOptimizationJointLoads( ...
    fullfile("../Step-7-Tracking-Optimization/MuscleDrivenTO/IDData/kick_1.sto"), ...
    fullfile("MuscleDrivenVO/IDData/kick_1.sto"))

plotTreatmentOptimizationControls( ...
    fullfile("MuscleDrivenVO/kick_1_muscleControls.sto"))

plotTreatmentOptimizationMuscleActivations( ...
    fullfile("../Step-7-Tracking-Optimization/MuscleDrivenTO/kick_1_combinedActivations.sto"), ...
    fullfile("MuscleDrivenVO/kick_1_combinedActivations.sto"))
