%% Run Torque-Driven Design Optimization

DesignOptimizationTool("TorqueDrivenDesignOptimizationSettings.xml");

plotTreatmentOptimizationResultsFromSettingsFile("TorqueDrivenDesignOptimizationSettings.xml")

%% Run Synergy-Driven Design Optimization

% DesignOptimizationTool("SynergyDrivenDesignOptimizationSettings.xml");

%% Plot Torque-Driven Results

plotTreatmentOptimizationJointAngles( ...
    "RightLegAndPelvis.osim", ...
    fullfile("../Step-8-Verification-Optimization/resultsVO/IKData/kick_1.sto"), ...
    fullfile("resultsDO/IKData/kick_1.sto"))

plotTreatmentOptimizationJointLoads( ...
    fullfile("../Step-8-Verification-Optimization/resultsVO/IDData/kick_1.sto"), ...
    fullfile("resultsDO/IDData/kick_1.sto"))

plotTreatmentOptimizationTorqueControls( ...
    fullfile("resultsDO/kick_1_torqueControls.sto"))

%% Plot Synergy-Driven Results

plotTreatmentOptimizationJointAngles( ...
    "RightLegAndPelvis.osim", ...
    fullfile("../Step-8-Verification-Optimization/SynergyDrivenVO/IKData/kick_1.sto"), ...
    fullfile("SynergyDrivenDO/IKData/kick_1.sto"))

plotTreatmentOptimizationJointLoads( ...
    fullfile("../Step-8-Verification-Optimization/SynergyDrivenVO/IDData/kick_1.sto"), ...
    fullfile("SynergyDrivenDO/IDData/kick_1.sto"))

plotTreatmentOptimizationSynergyControls( ...
    fullfile("SynergyDrivenDO/kick_1_synergyCommands.sto"))

plotTreatmentOptimizationMuscleActivations( ...
    fullfile("../Step-8-Verification-Optimization/SynergyDrivenVO/kick_1_combinedActivations.sto"), ...
    fullfile("SynergyDrivenDO/kick_1_combinedActivations.sto"))
