plotTreatmentOptimizationJointAngles( ...
    "UF_Subject_3_reduced_muscles.osim", ...
    fullfile("preprocessed", "IKData", "gait_1.sto"), ... 
    fullfile("preprocessed", "IKData", "gait_1.sto"))

plotTreatmentOptimizationJointLoads( ...
    fullfile("preprocessed", "IDData", "gait_1.sto"), ...
    fullfile("preprocessed", "IDData", "gait_1.sto"))

plotTreatmentOptimizationGroundReactions( ...
    fullfile("preprocessed", "GRFData", "gait_1.sto"), ...
    fullfile("preprocessed", "GRFData", "gait_1.sto"))

plotTreatmentOptimizationMuscleActivations( ...
    fullfile("preprocessed", "EMGData", "gait_1.sto"), ...
    fullfile("preprocessed", "EMGData", "gait_1.sto"))